# Generated by Django 3.2.16 on 2022-11-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название предмета', max_length=255, verbose_name='название предмета')),
                ('description', models.TextField(help_text='Введите описание предмета', verbose_name='описание предмета')),
                ('price', models.FloatField(help_text='Введите стоимость предмета', verbose_name='стоимость предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ('-price',),
            },
        ),
    ]
