# Generated by Django 3.2.16 on 2022-11-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'Usd'), ('rub', 'Rub')], default='usd', max_length=3),
        ),
    ]
