# Generated by Django 3.2.16 on 2022-11-20 09:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'Usd'), ('rub', 'Rub')], default='usd', help_text='Выберите валюту', max_length=3, verbose_name='валюта'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_of_discount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(75), django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='payments.item', verbose_name='скидка на товар')),
            ],
        ),
    ]
