# Generated by Django 3.2.16 on 2022-11-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20221120_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='payments.item', unique=True, verbose_name='скидка на товар'),
        ),
    ]
