# Generated by Django 3.2.16 on 2022-11-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_discount_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='payments.item', verbose_name='скидка на товар'),
        ),
    ]
